Jenkinsfile
package.json
src/App.test.js

**Changes:**
- updated test file
- updated jenkinsfile
- updated package.json

updated unit test and jenkinsfile

---

package.json
src/App.js
src/mock/data/index.js
src/mock/mockServer.js

**Changes:**
- add miragejs, dotenv, and axios package
- add script to run mock server
- created mock server
- created mock data for common menu

created mock server

---

package.json

**Changes:**
- updated react script

updated script

---

package.json
src/App.js
src/context/auth/AuthProvider.js
src/context/auth/auth.js
src/context/auth/index.js
src/index.js
src/utils/constants.js
src/utils/cookies.js

**Changes:**
- added universal cookies npm package
- added auth provider
- added constants file to store api paths
- added a function that checks for cookies
- added a class for auth to handle auth related operations

added auth provider

---

package.json
src/App.js
src/utils/constants.js

Changes Made:  
-  Add react-ga package to integrate Google Analytics
-  Load tracking on page load

implement google analytics new branch

---

jsconfig.json
package.json
src/App.js
src/App.test.js
src/context/auth/AuthProvider.js
src/context/auth/auth.js
src/context/auth/index.js
src/index.js
src/mock/data/index.js
src/mock/mockServer.js
src/utils/constants.js
src/utils/cookies.js

**Changes:**
- updated compiler and prettier config
- formatted document to use single quote instead of double quote
- fixed unit test for app component
- only use google analytics in production mode

updated compiler and prettier config

---

package.json
src/App.js
src/index.js
src/routes/AppRouter.js
src/routes/ProtectedRoute.js
src/stubs/Landing.js
src/stubs/Login.js
src/stubs/Mentor.js
src/stubs/Register.js
src/utils/constants.js

- Added react router packages
- Created a Container Routes Component
- Created Protected Route Component

finished routes

---

Jenkinsfile
package.json
src/App.test.js
src/components/Header/Header.js
src/routes/AppRouter.js
src/utils/ComponentFactory.js
src/utils/constants.js

**Changes:**
- revised routes and header component
- fixed app test

Major refactor

---

jest.config.js
package.json
src/App.test.js
src/components/Header/Header.test.js
src/setupTests.js

**Changes:**
- converted rtl to enzyme
- removed rtl packages
_Note: will have to improve unit test for header component later_

convert rtl to enzyme

---

src/components/Header/Header.test.js

fixed test error

---

src/components/Header/Header.js

**Changes:**
- fixed page reload when clicking on header links

page reload fix

---

src/components/Header/Header.js

changed header color

---

package.json
src/components/Header/Header.js
src/components/Header/Header.test.js

**Changes:**
- combined useState hooks into one object

Header refactor

---

src/components/Header/Header.js

**Changes:**
- fixed header component issue when user is not logged in
- fixed dom structure for wcag

fix header

---

src/components/Header/Header.js

**Changes:**
- changed contrast for nav item "Join Us"

contrast change

---

src/components/Header/Header.js

**Changes:**
- fixed page reload on mobile view join button

mobile view join button page reload fix

---

src/components/Header/Header.js

- Cleaned up import statements

Cleaned up import statements

---

src/App.js

**Changes:**
- memoized app component

memoized app

---

package.json
src/components/Header/Header.js
src/stubs/Login.js
src/utils/axiosConfig.js
src/utils/constants.js
src/utils/cookies.js

**IMPORTANT NOTE:**
will require update in .env file and hosts file:
**add the following in .env file:**
_DANGEROUSLY_DISABLE_HOST_CHECK=true_
_HOST=local.femmecubator.com_
**add the below line in /private/etc/hosts:**
_127.0.0.1   local.femmecubator.com_
**execute the below command:**
_dscacheutil -flushcache_
**Changes:**
- updated scripts to run both frontend and backend
- created a proxy for the backend localhost testing
- created axios interceptor
- updated stub Login component to get cookie from api needed to test common menu api (no styling, just a form for a user to type in credentials)
- added login route in constants
- updated logic in isAuthCookiesExists to only be true when it is able to parse cookie session id provided by api

auth changes

---

src/stubs/Login.js

**Changes:**
- changed userName to userId

updated stub login component

---

src/stubs/Register.js

updated stub component to test error boundary

throw error for test

---

src/App.js

**Changes:**
- fixed mobile view issue on first load

fixed mobile view issue on first load

---

src/components/ErrorHandling/ErrorFallback.js

Hello, 
I've made the requested changes as noted below. Let me know if any additional changes are needed. Thanks! 
Changes Made:
• Adjusted Image size on desktop to 20%
• Adjusted Image size on mobile to 30%
• Removed text 'By logging out'

fix image size and modify error txt

---

src/components/Home/Home.js

-Changed two colors because of contrast issues.
-Changed all H1 to H2 and H3
-Added fixes for the Carousel because of the issues on some mobile browsers.
-Added 'alt' to the hero image
-Added 'aria-label' to the 'WORKATHON" header.
-Replaced 'gap' property with 'margin' because some browsers don't fully support it yet!

Home component fixes

---

src/components/Home/Home.test.js

fixed home unit test

---

src/components/Home/Home.js

**Changes:**
- updated contents of home component

updated contents in home component

---

src/components/Home/Home.js

-fixed padding for the workathon container

fixed padding for the workathon container

---

src/components/Home/Home.js

Finished in progress banner

---

src/components/Home/Home.js

fix background color

---

package.json
src/stubs/Login.js
src/utils/axiosConfig.js
src/utils/constants.js

- made updates on axios interceptor as a result of a change in deployment region; no longer using nginx proxy pass

refactored app

---

src/components/Header/Header.js

- fixed an issue where the header component was not changing to signed in state because the auth.isLoggedIn() is not updated when the user receives a cookie

fixed header issue when user signs in

---

src/components/AccountForms/RegistrationForm/index.js

fixed wcag

---

src/components/Header/AuthenticatedHeader.test.js
src/components/Header/Header.test.js
src/context/auth/__mocks__/AuthProvider.js
src/context/auth/__mocks__/index.js
src/testServer.js

fixed unit test for authenticated users

fixed header unit test for authenticated user

---

src/App.js
src/components/AccountForms/RegistrationForm/index.js
src/components/Home/Home.js
src/index.js
src/utils/analytics.js
src/utils/constants.js

refactored analytics and hooked up Home and Register component to Google Analytics.

hooked up analytics to home and register component

---

src/components/AccountForms/RegistrationForm/index.js

fixed wcag mobile

---

src/components/AccountForms/RegistrationForm/index.js

updated onSubmit handler logic

updated logic for onSubmit registration

---

package.json

updated git hook script to only run unit test without coverage report

updated git hook script

---

src/components/AccountForms/RegistrationForm/index.js

fixed button alignment when landscape view in iPad and Pixel 2 XL

fixed button alignment when landscape

---

src/components/AccountForms/RegistrationForm/index.js

updates as per @robghchen recommendation

fixed pr issue

---

src/components/AccountForms/LoginForm/LoginForm.styles.js
src/components/AccountForms/LoginForm/index.js

- Added aria-label to svg.
- Changed Create Account button background color to more accessible color.

Login accessibility

---

src/utils/cookies.js

fixed logoff: clears cookies for uat domain also

[BUG]-Authentication-fix logoff

---

src/components/ErrorHandling/ErrorFallback.js

changes: 
- centered container across devices

style(errorFallback): centered with grid

---

.github/pull_request_template.md

feat(prs): pr template 89

---

.github/pull_request_template.md
.gitignore

feat(pr): add To Do section to template

---

src/utils/cookies.js

[BUG]-Auth-clear session

---

.eslintrc.json
.github/pull_request_template.md
src/components/Header/Header.test.js
src/testServer.js

pr template update

---

package.json
src/App.js
src/components/AccountForms/LoginForm/index.js
src/components/AccountForms/RegistrationForm/index.js
src/components/Header/Header.js
src/components/Header/Header.test.js
src/components/Home/Home.test.js
src/components/RegistrationSuccess/RegistrationSuccess.test.js
src/components/Subheader/Subheader.test.js
src/context/actionCreators/index.js
src/routes/AppRouter.js
src/routes/FemmecubatorRoute.js
src/stories/Subheader.stories.js
src/testServer.js
src/utils/axiosConfig.js

- updated prettier rule to avoid arrowParens on single params function
- eslint fixes

fixed arrowParens prettier rule and eslint fixes

---

package-lock.json
src/components/AccountForms/RegistrationForm/ChipComponent.js
src/components/AccountForms/RegistrationForm/RegistrationForm.styles.js

fixed deployment issues

---

src/components/AccountForms/LoginForm/LoginForm.test.js

closes #130 
- Renamed LoginForms.test.js to LoginForm.test.js
- Fixed console.errors in LoginForm unit tests.

rename LoginForm and resolved console errors from test

---

src/components/AccountForms/RegistrationForm/ChipComponent.js

closes #134
Fixes mentor dashboard displaying after registration as a mentee.
Fixes mentee dashboard displaying after registration as a mentor.

switch role_ids for chips

---

src/components/AccountForms/RegistrationForm/ChipComponent.js

Reverts femmecubator/femmecubator-ui-repo#135

Revert "switch role_ids for chips"

---

src/components/AccountForms/RegistrationForm/ChipComponent.js
src/components/AccountForms/RegistrationForm/index.js

Fixes role_id on registration.
After registration as mentor, user is sent to mentor dashboard.
After registration as mentee, user is sent to mentee dashboard.

Role id fix

---

src/components/ViewContainer/index.js

Added hasOnboarded info in order to update Mentor Path
- [] I added storybook for the component

changed logic for mentor path

---

src/App.js

disabling timeout session for prod deployment; will need to fix defect on tabIndex on profile drop down

disable-timeout

---

src/components/AccountForms/LoginForm/index.js

fixed error banner in login

---

src/components/Settings/AccountInfo.js
src/components/Settings/TimeSlotModal/index.js
src/components/Settings/index.js
src/utils/constants.js
src/utils/cookies.js

changes acc. to roles

---

src/components/AboutContainer/AboutSideBar/AboutSideBar.styles.js

about page side menu, styling fixed

---

src/components/AboutContainer/AboutContentContainer/AboutContentPages/Community.js
src/components/AboutContainer/AboutContentContainer/AboutContentPages/ContactUs.js
src/components/AboutContainer/AboutContentContainer/AboutContentPages/WhoWeAre.js
src/components/Footer/Footer.js
src/components/Home/Home.js
src/components/Home/MentorGetInvolved.js

last minute text changes and profile updates in who we are

---

src/components/AboutContainer/AboutContentContainer/AboutContentContainer.styles.js
src/components/AboutContainer/AboutContentContainer/AboutContentPages/Volunteer.js
src/components/Directory/BookDialog/SlotTable/SlotTable.styles.js
src/components/Directory/BookDialog/SlotTable/index.js
src/components/Home/Home.js
src/components/Home/MentorGetInvolved.js
src/components/Home/MentorGetInvolved.styles.js

Text changes and responsiveness fixes

---

src/components/AboutContainer/AboutContentContainer/AboutContentContainer.styles.js

who we are member card width fix
